FROM node:16.20.2-alpine

LABEL version="1.0"
LABEL description="Development image for the TODO MERN API"

WORKDIR /app

COPY ["package.json","package-lock.json*","npm-shrinkwrap.json*", "./"]

RUN npm install && npm cache clean --force

COPY . .

EXPOSE 5050

CMD [ "npm", "run", "dev" ]